image: php:8.1-cli-alpine

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apk add --update git unzip openssh-client autoconf make g++
          - pecl install xdebug-3.1.5
          - docker-php-ext-enable xdebug
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - vendor/bin/php-cs-fixer fix --dry-run -v --diff --diff-format=udiff
          - vendor/bin/phpunit --log-junit ./test-reports/junit.xml
