name: Set up
runs:
  using: composite
  steps:
    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.26.0
      with:
        php-version: 8.1
        extensions: xdebug-3.1.5
        coverage: pcov
        tools: composer

    - name: Install dependencies
      run: composer install
      shell: bash
