name: Test & Analyze

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP Action
        uses: ./.github/actions/setup-php

      - name: Run tests
        run: vendor/bin/phpunit

  kam-cs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/kartenmacherei/kam-cs:6.0.1
    steps:
      - uses: actions/checkout@v4
      - name: Run kam-cs
        run: php /tools/kam-cs fix --verbose --no-ansi --no-interaction --dry-run --diff
